name: leyThings
version: '1.0-SNAPSHOT'
main: me.ley.leythings.LeyThings
api-version: '1.20'
authors: [Ley]
description: Just Ley things
permissions:
  lab_barrel_tp:
    description: Permite al jugador usar la teletransportación con barriles.
    default: false